### ISSUE TITLE
add to npm

### ISSUE THREAD

**Issue by DracoBlue** [patorjk/Extendible-BBCode-Parser#13]
It would be great to have this bbcode parser on npm.

I found this fork at https://github.com//epochtalk/bbcode-parser but it would be good to have the original one available there.

**Comment by patorjk** [comment]
This is a good idea, I'll try and look into this tonight.

**Comment by DracoBlue** [comment]
Awesome ;)

**Comment by patorjk** [comment]
Sorry this took forever, I've added it to npm though:

https://www.npmjs.com/package/Extendible-BBCode-Parser
