### ISSUE TITLE
Problem using node build in browser

### ISSUE THREAD

**Issue by ng-dan** [patorjk/Extendible-BBCode-Parser#18]
Hi,

I'm including a version of this project in my code after doing an npm install, and I'm getting the following error: ```Uncaught ReferenceError: module is not defined at xbbcode.js:797```

The code block in question is:
```JavaScript
// for node
if (module) {
    module.exports = XBBCODE;
}
```

I presume this is because I'm not using this as part of a node project.

Any help on this matter would be greatly appreciated, thanks!

**Comment by patorjk** [comment]
What web browser are you using? If you're not using node you can just delete those 3 lines, however, that shouldn't give you any errors. If you change it to this do you still get an error?

    if (typeof module !== "undefined") {
        module.exports = XBBCODE;
    }

**Comment by ng-dan** [comment]
I'm using the latest version of Google Chrome. I could delete those lines however this is part of an automated build process and this would add unnecessary complexity to it.

Changing it to that works.

**Comment by patorjk** [comment]
Thanks for the info. I've gone ahead and updated the repo, however, I'm not on a computer where I can push to npm so I'll do that tonight.

**Comment by ng-dan** [comment]
Awesome, thanks for your help.
