### ISSUE TITLE
Not enough tags. Alternative

### ISSUE THREAD

**Issue by MiTereKun** [patorjk/Extendible-BBCode-Parser#26]
Alas, there is no support for the huge number of important markup tags used on [rutracker.org](http://rutracker.org). Yes, the site has not been updated for a very long time, but in its current state [wysibb](http://wysibb.com/demo) looks more attractive, although it is still the same most neutered visual editor.

I spent 2 hours digging through the whole github in search of a full-fledged visual BBCode editor and I still haven't found anything better than wysibb. From this I conclude that the language is simply dead.

**Comment by patorjk** [comment]
It's extendable, you can support new tags by updating the code. That said, I haven't used this in ages, I made it for fun one day and I provide it here for people who wanted something to use.
