### ISSUE TITLE
is it possible to parse bbcode with html tags in the string?

### ISSUE THREAD

**Issue by patrikpatrik** [patorjk/Extendible-BBCode-Parser#27]
For some reason when html tags are included in the string it doesn't seem to work properly.

For example if you had a string like "<h1>The log is [color=brown][b] dirty[/b][/color] </h1> "

it doesnt seem to parse the tags right but the bbcode will go through, or the tags will parse correctly with html() but the bbcode is changed to something weird..

**Comment by patorjk** [comment]
It's setup not to interpret HTML tags, so it'll change the <>'s into HTML entities.

**Comment by patrikpatrik** [comment]
@patorjk , Thank you for the quick response. Is there a way to interpret it with an option or anything?

**Comment by patorjk** [comment]
No, it's not setup to allow both HTML and BBCode. You could try commenting out these two lines:

https://github.com/patorjk/Extendible-BBCode-Parser/blob/master/xbbcode.js#L740

But I'm not sure what the exact effects would be, plus you'd be allowing any HTML into the result, which isn't a good idea.

**Comment by patrikpatrik** [comment]
That's right. So what would be the proper way of doing this? Sanitizing the string of all html tags except for the bbcodes, then parsing accordingly, then add the tags afterwards using vanilla js or jQuery no?

**Comment by patorjk** [comment]
That could work. Maybe replace <> with {}, run the bbcode parser, then swap back in the <>'s.

**Comment by patrikpatrik** [comment]
I might do that. Okay thank you.
