### ISSUE TITLE
Update http://patorjk.com/bbcode-previewer/ to link to this repository

### ISSUE THREAD

**Issue by danneu** [patorjk/Extendible-BBCode-Parser#7]
On your website, this:

> You can download the JavaScript module for this here.

links to a .zip that's far behind master.

For example, I didn't stumble upon this repo until I was ready to host my patched version of your .zip file on Github. But now I see that my patches have mostly been taken care of.

Anyways, thanks for sharing your effort. It works well and has saved me a lot of time.

**Comment by patorjk** [comment]
This is a good idea, sorry it wasn't linked to before. I've gone ahead and updated the example and corresponding blog post to point to the repo.
